version: '2'

services:
  fpm:
    image: carcel/akeneo-fpm:php-7.1
    depends_on:
      - elasticsearch
      - mysql
      - mysql-behat
      - selenium
    environment:
      BEHAT_TMPDIR: '/home/docker/pim/app/cache/tmp'
      PHP_IDE_CONFIG: 'serverName=pim-ce-cli'
      PHP_XDEBUG_ENABLED: 0
      XDEBUG_CONFIG: 'remote_host=192.168.7.108'
    user: docker
    volumes:
      - ./:/home/docker/pim
      - ~/.composer:/home/docker/.composer
      - /tmp/behat/screenshots:/tmp/behat/screenshots
    working_dir: /home/docker/pim
    networks:
      - akeneo
      - behat

  elasticsearch:
    image: elasticsearch:5.2
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    ports:
      - '9202:9200'
    networks:
      - akeneo
      - behat

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=akeneo_pim
      - MYSQL_PASSWORD=akeneo_pim
      - MYSQL_DATABASE=akeneo_pim
    ports:
      - '3310:3306'
    volumes:
      - ./docker/mysql.cnf:/etc/mysql/conf.d/sql_modes.cnf
    networks:
      - akeneo

  mysql-behat:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=akeneo_pim
      - MYSQL_PASSWORD=akeneo_pim
      - MYSQL_DATABASE=akeneo_pim
    ports:
      - '3311:3306'
    volumes:
      - ./docker/mysql.cnf:/etc/mysql/conf.d/sql_modes.cnf
    networks:
      - behat

  nginx:
    image: carcel/nginx
    depends_on:
      - fpm
    environment:
      PHP_IDE_CONFIG: 'serverName=pim-ce'
    ports:
      - '8084:80'
    volumes:
      - ./:/home/docker/pim
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - akeneo

  nginx-behat:
    image: carcel/nginx
    depends_on:
      - fpm
    environment:
      PHP_IDE_CONFIG: 'serverName=pim-ce-behat'
    ports:
      - '8085:80'
    volumes:
      - ./:/home/docker/pim
      - ./docker/nginx-behat.conf:/etc/nginx/conf.d/default.conf
    networks:
      - behat

  selenium:
    image: selenium/standalone-firefox-debug:2.53.1-beryllium
    ports:
      - '5902:5900'
    volumes:
      - ./:/home/docker/pim
    networks:
      - behat

networks:
  akeneo: ~
  behat: ~
